### ISSUE TITLE
Broken Link in scripts/README.md

### ISSUE THREAD

**Issue by soerenbe** [zarafagroupware/python-zarafa#23]
"""
zarafa-spamhandler
A description of the zarafa-spamhandler can be found in this blog post
"""

This points to a link which is acually broken:

http://www.zarafa.com/blog/post/2014/08/cool-scripts-and-tools-automated-spam-processing-python-zarafa-and-zarafa-spamhand

**Comment by bkram** [comment]
Thanks for catching this we just fixed this.
