### ISSUE TITLE
zarafa-spamhandler: process rules after junk-unlearn

### ISSUE THREAD

**Issue by sreichholf** [zarafagroupware/python-zarafa#36]
hi,

it would be great if the zarafa-spamhandler would process the rules after junk-unlearn.
I'm sorting most of my mail using inbound rules and have to that manually for false positives.

Actually a short hint if this is possible at all using the current python-zarafa and where start would be enough. I do speak python quite well ;)

**Comment by bkram** [comment]
Hi,

It is not possible to trigger filters at the moment, we might have something like that sometime in the future.
