### ISSUE TITLE
examples.py & python version / requirements

### ISSUE THREAD

**Issue by mborus** [zarafagroupware/python-zarafa#37]
Hi,

the readme mentions a file "examples.py" which has some examples on how to use zarafa.
This file is missing.

Also it would be nice to specify which version of python is recommended.

**Comment by bkram** [comment]
Hi,

python-zarafa is no longer supported it has been superseded by python-kopano, and is as such included in the kopano core product itself, see https://download.kopano.io/community/core:/

For more examples please take a look at 

- https://stash.kopano.io/projects/KSC/repos/lab-scripts/browse
- https://stash.kopano.io/projects/KSC/repos/core-tools/browse
- https://stash.kopano.io/projects/KC/repos/kopanocore/browse/swig/python/kopano/scripts

Kind regards,

Mark
